- name: Deploy Fluentd
  hosts: all
  tasks:
    - name: Install Fluentd
      shell: curl -L https://toolbelt.treasuredata.com/sh/install-debian-stretch-td-agent2.sh | sh
    - name: Fluentd Service Start
      service: name=td-agent state=started enabled=yes
    - name: Finish display message
      debug:
        msg: "Let's Fluentd!"
